# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160731_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=NameError),
        ),
    ]
